### ISSUE TITLE
Example data link not working

### ISSUE THREAD

**Issue by AlessiaCaramello** [IPMI-ICNS-UKE/ICNS-CoLD#1]
Hi there, 
I would like to try your code as I might need it for my project. The example data link is not working, can you have a loot at it?
Thanks a lot!
Alessia

**Comment by renewerner** [comment]
Thank you for reporting this issue. We will try to solve it within the next week.

**Comment by renewerner** [comment]
Example data are now included in the repository via git lfs. Please either download them directly or clone the repository after installing git lfs. In case of questions, please contact us.
Thank you!

**Comment by AlessiaCaramello** [comment]
Thanks a lot!
